version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: school           # Name of your database
      POSTGRES_USER: postgres        # Username
      POSTGRES_PASSWORD: yourpassword # Change this to a secure password
    ports:
      - "5432:5432"                  # Expose PostgreSQL on port 5432
    volumes:
      - ./db/data/postgresql:/var/lib/postgresql/data # Persist PostgreSQL data
      - ./db/sql:/docker-entrypoint-initdb.d # Mount sql directory
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg_data:                           # Named volume for PostgreSQL data
